import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import AddIcon from '@mui/icons-material/Add'
import { useState } from 'react'
import TextField from '@mui/material/TextField'
import Button from '@mui/material/Button'
import ClearIcon from '@mui/icons-material/Clear'

export default function Home() {
  const [form, setForm] = useState(false);

  let n: number;


  return (
    <>
      <Head>
        <title>Beepr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />
        <h2 className={styles.mainText}>Create a queue and notis people!</h2>
        <div className={styles.card} onClick={() => { setForm(!form) }}>
          <AddIcon sx={{ fontSize: 150 }} />
          <div className={styles.cardText}>Create</div>
        </div>
        <div className={form ? styles.openForm : styles.closeForm}>
          <div className={styles.mask} onClick={() => { setForm(!form) }}></div>
          <div className={styles.formBody}>
            <div className={styles.formExit}>
              <div className="buttonContainer" onClick={() => { setForm(!form) }}>
                <ClearIcon sx={{ fontSize: 35 }} />
              </div>
            </div>
            <div className={styles.formInput}>
              <TextField fullWidth id="outlined-basic" label="Queue Name" variant="outlined" />
            </div>
            <Button variant="contained" className={styles.formButton}>Submit</Button>
          </div>
        </div>
      </main>
    </>
  )
}
